default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - pre-commit

repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-ast
      - id: debug-statements

  # Conventional-commit hooks
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.1
    hooks:
      - id: commitizen
        additional_dependencies: ["cz-conventional-gitmoji"]
      - id: commitizen-branch
        stages:
          - pre-push
        additional_dependencies: ["cz-conventional-gitmoji"]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.6.1
    hooks:
      - id: conventional-gitmoji

  # Python related hooks
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.29
    hooks:
      # Update the uv lockfile
      - id: uv-lock
      # - id: uv-export

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --output-format=concise
      - id: ruff-format

  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.23.0
    hooks:
      - id: deptry

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
